services:
  openauth-api:
    container_name: openauth-api
    image: callmewhy/openauth-api:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 5566:5566
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure

  openauth-prometheus:
    container_name: openauth-prometheus
    image: prom/prometheus:v2.43.0
    ports:
      - 5560:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles

  openauth-grafana:
    container_name: openauth-grafana
    image: grafana/grafana:9.5.1
    user: "472"
    ports:
      - 5561:3000
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "grafana_config:/etc/grafana"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=bjUbjqr88wMlPB3jL3MTWxSHIbDCoH

volumes:
  grafana_data:
  grafana_config:
