services:
  test-psql:
    container_name: openauth-test-psql
    image: postgres:12.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure

  test-api:
    container_name: openauth-test-api
    build:
      dockerfile: Dockerfile
      target: api-test
    ports:
      - "5565:5566"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@test-psql:5432/postgres
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure
    depends_on:
      - test-psql
