name: Deploy Web

on:
  push:
    branches:
      - main2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - name: Install npm dependencies
        run: pnpm install
      - name: build
        run: pnpm build
      - name: rsync
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --filter=':- .gitignore'
          path: dist/*
          remote_path: /data/openauth-web
          remote_host: 20.212.6.4
          remote_port: 2222
          remote_user: why
          remote_key: ${{ secrets.DEPLOY_KEY }}
